[package]
name = "test-component"
version = "0.0.1"
description = ""
authors = [""]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["guest"]
guest = []

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
vino-provider = { path = "../../vino-provider", features = ["wasm"] }

[dev-dependencies]
