[package]
name = "test-component"
version = "0.0.1"
description = ""
authors = [""]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["guest"]
guest = []

[dependencies]
wapc-guest = "0.4.0"
serde = { version = "1.0.126", features = ["derive"] }
lazy_static = "1.4.0"
vino-component = { path = "../../vino-component" }

[dev-dependencies]
