[package]
name = "test-component"
version = "0.0.1"
description = ""
authors = [""]
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["wasm"]
wasm = ["vino-provider/wasm"]
native = ["vino-provider/default"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "wasm",
] }

[dev-dependencies]
