[package]
name = "vino"
version = "0.1.0"
edition = "2021"
default-run = "vino"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-loader = { path = "../vino-loader" }
vino-packet = { path = "../../sdk/crates/vino-packet" }
logger = { path = "../logger" }
vino-provider-cli = { path = "../vino-provider-cli" }
vino-runtime = { path = "../vino-runtime" }
vino-transport = { path = "../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-host = { path = "../vino-host" }
vino-manifest = { path = "../vino-manifest" }
vino-codec = { path = "../../sdk/crates/vino-codec" }
vino-types = { path = "../../sdk/crates/vino-types" }
tap = { path = "../tap" }
vino-test = { path = "../vino-test" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
structopt = "0.3"
nkeys = { path = "../../forks/nkeys" }
futures = "0.3"
serde_json = "1.0"
serde = "1.0"
thiserror = "1.0"
atty = "0.2"

[dev-dependencies]
test_bin = "0.3"

[[bin]]
name = "vino"
path = "src/main.rs"
