[package]
name = "test-interface-keyvalue"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "test-interface-collection"
path = "src/main.rs"

[dependencies]
thiserror = "1.0"
wasmflow-packet = { path = "../../../sdk/crates/wasmflow-packet" }
wasmflow-codec = { path = "../../../sdk/crates/wasmflow-codec" }
vino-rpc = { path = "../../vino/vino-rpc" }
vino-invocation-server = { path = "../../vino/vino-invocation-server" }

tracing = "0.1"

anyhow = "1.0"
