---
version: 0
network:
  schematics:
    - name: short_circuit
      providers:
        - namespace: wapc
          kind: WaPC
          reference: ../integration/test-wapc-component/build/test_component_s.wasm
      instances:
        validate_password:
          id: wapc::validate
        log:
          id: vino::v0::log
        log2:
          id: vino::v0::log
      connections:
        - from:
            instance: <input>
            port: input_port1
          to:
            instance: validate_password
            port: input
        - from:
            instance: validate_password
            port: output
          to:
            instance: log2
            port: input
        - from:
            instance: log2
            port: output
          to:
            instance: <output>
            port: output
          default: '"This is my default. Error was: $ERROR"'
