[package]
name = "test-interface-collection"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "test-interface-collection"
path = "src/main.rs"

[dependencies]
thiserror = "1.0.25"
vino-provider = { path = "../../vino-provider", features = ["native"] }
vino-packet = { path = "../../vino-packet" }
vino-codec = { path = "../../vino-codec" }
vino-rpc = { path = "../../vino-rpc" }
vino-invocation-server = { path = "../../vino-invocation-server" }

log = "0.4"

maplit = "1.0.2"
anyhow = "1.0.42"
