[package]
name = "vino-runtime"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
vino-component = { path = "../vino-component" }
vino-macros = { path = "../vino-macros" }
vino-manifest = { path = "../vino-manifest" }
vino-provider = { path = "../vino-provider", features = ["native"] }
vino-provider-wasm = { path = "../vino-provider-wasm" }
vino-native-api-0 = { path = "../provider-native-api-0" }
vino-transport = { path = "../vino-transport" }
vino-codec = { path = "../vino-codec" }
vino-wascap = { path = "../vino-wascap" }
vino-rpc = { path = "../vino-rpc" }
vino-entity = { path = "../vino-entity" }
vino-types = { path = "../vino-types" }

serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.64"
actix = "0.12.0"
actix-rt = "2.2.0"
futures = "0.3"
uuid = { version = "0.8", features = ["serde", "v4"] }
async-trait = "0.1.50"
once_cell = "1.5.2"
parking_lot = "0.11.1"
thiserror = "1.0.26"
derivative = "2.2.0"
tonic = { version = "0.5.0", features = ["tls"] }
tokio = { version = "1.4.0", features = [
  "macros",
  "net",
  "time",
  "rt-multi-thread",
] }
tokio-stream = { version = "0.1.6", features = ["net"] }
itertools = "0.10.1"
tracing = "0.1.26"
tracing-actix = "0.3.0"
log = "0.4.14"

[dev-dependencies]
env_logger = "0.9"
test-env-log = { version = "0.2.7", features = ["trace"] }
maplit = "1.0.2"
test-vino-provider = { path = "../integration/test-vino-provider" }
tracing-subscriber = "0.2.18"
tracing-unwrap = "0.9.2"
tracing-futures = "0.2.5"
pretty_assertions = "0.7.2"
criterion = { version = "0.3", features = ["async", "async_tokio"] }
lazy_static = "1.4.0"
anyhow = "1.0.42"

[[bench]]
name = "wapc"
harness = false
