[package]
name = "vino-runtime"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"

[features]

[dependencies]
vino-packet = { path = "../../sdk/crates/vino-packet" }
vino-macros = { path = "../../sdk/crates/vino-macros" }
vino-manifest = { path = "../vino-manifest" }
vino-loader = { path = "../vino-loader" }
vino-provider = { path = "../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-provider-wasm = { path = "../vino-provider-wasm" }
vino-provider-lattice = { path = "../vino-provider-lattice" }
vino-lattice = { path = "../vino-lattice" }
vino-native-api-0 = { path = "../provider-native-api-0" }
vino-transport = { path = "../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-codec = { path = "../../sdk/crates/vino-codec" }
vino-wascap = { path = "../vino-wascap" }
vino-rpc = { path = "../vino-rpc" }
vino-entity = { path = "../../sdk/crates/vino-entity" }
vino-types = { path = "../../sdk/crates/vino-types" }
vino-invocation-server = { path = "../vino-invocation-server" }

serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.64"

futures = "0.3"
async-trait = "0.1.50"
once_cell = "1.8"
parking_lot = { version = "0.11.1", features = [] }
thiserror = "1.0.26"
tokio = { version = "1", features = [
  "macros",
  "time",
  "sync",
  "rt-multi-thread",
] }
tokio-stream = { version = "0.1.6", features = [] }
itertools = "0.10.1"
tracing = "0.1"
dyn-clone = "1.0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
rand = { version = "0.8.4", default-features = false, features = [
  "std_rng",
  "alloc",
] }
async-recursion = "0.3.2"

[dev-dependencies]
test-vino-provider = { path = "../integration/test-vino-provider" }

logger = { path = "../logger" }
test-logger = { path = "../test-logger" }
maplit = "1.0.2"
pretty_assertions = "0.7.2"
criterion = { version = "0.3.5", features = ["async", "async_tokio"] }
lazy_static = "1.4.0"
anyhow = "1.0.42"

[[bench]]
name = "wapc"
harness = false

[[bench]]
name = "echo"
harness = false
