[package]
name = "vino"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "Application data flow platform"
repository = "https://gitlab.com/vino-dev/vino"
documentation = "https://vino.dev"
readme = "README.md"


[dependencies]


[dev-dependencies]
test_bin = "0.3.0"
maplit = "1.0.2"
test-env-log = { version="0.2.7", features=["trace"] }
tokio = { version="1.4.0", features=["macros", "net", "rt-multi-thread"] }
futures = "0.3.15"
vino-codec = { path="./crates/vino-codec" }
vino-component = { path="./crates/vino-component" }
vino-provider = { path="./crates/vino-provider" }
test-vino-provider = { path="./crates/test-vino-provider" }
vino-rpc = { path="./crates/vino-rpc" }
log = "0.4.14"
env_logger = "0.8.4"
anyhow = "1.0.41"
tracing = "*"
tracing-subscriber = "0.2.18"

[workspace]
members = [
  "crates/vino-cli",
  "crates/vino-ctl",
  "crates/vino-macros",
  "crates/logger",
  "crates/vino-runtime",
  "crates/vino-rpc",
  "crates/vino-host",
  "crates/vino-transport",
  "crates/vino-codec",
  "crates/vino-manifest",
  "crates/vino-provider",
  "crates/vino-native-provider",
  "crates/vino-provider-cli",
  "crates/test-vino-provider",
  "crates/test-wapc-component",
  "crates/wascap",
  "crates/vino-wellknown-document-collection",
]
