[package]
name = "vino-root"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
description = "Application data flow platform"
repository = "https://gitlab.com/vino-dev/vino"
documentation = "https://vino.dev"
readme = "README.md"

[profile.release]
opt-level = 3
lto = true

[dependencies]

[dev-dependencies]
vino-entity = { path = "./sdk/crates/vino-entity" }
vino-codec = { path = "./sdk/crates/vino-codec" }
vino-packet = { path = "./sdk/crates/vino-packet" }
vino-provider = { path = "./sdk/crates/vino-provider", features = ["native"] }
vino-transport = { path = "./sdk/crates/vino-transport" }
logger = { path = "./crates/logger" }
vino-interface-collection = { path = "./crates/interfaces/interface-collection" }
test-vino-provider = { path = "./crates/integration/test-vino-provider" }
vino-rpc = { path = "./crates/vino-rpc" }
vino-macros = { path = "./sdk/crates/vino-macros" }
utils = { path = "./tests/utils" }
test_bin = "0.3.0"
maplit = "1.0.2"
test-env-log = { version = "0.2.7" }
tokio = { version = "1.4.0", features = [
  "macros",
  "process",
  "time",
  "net",
  "rt-multi-thread",
] }
futures = "0.3.15"
log = "0.4.14"
test-logger = { path = "./crates/test-logger" }
anyhow = "1.0.41"
serde_json = "1.0.64"

[workspace]
members = [
  "crates/forks/*",
  "crates/interfaces/*",
  "crates/integration/*",
  "crates/*",
]
exclude = [
  "crates/integration/test-wapc-component",
  "sdk/",
  "forks/",
  "crates/forks",
  "crates/integration",
  "crates/interfaces",
]
