[package]
name = "vino-root"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
description = "Application data flow platform"
repository = "https://github.com/vinodotdev/vino-core"
documentation = "https://vino.dev"
readme = "README.md"

[profile.release]
opt-level = 3
debug = 0
incremental = true

[features]
test-integration = []

[dependencies]

[dev-dependencies]
vino-entity = { path = "./sdk/crates/vino-entity" }
vino-codec = { path = "./sdk/crates/vino-codec" }
vino-packet = { path = "./sdk/crates/vino-packet" }
vino-provider = { path = "./sdk/crates/vino-provider", features = ["native"] }
vino-transport = { path = "./sdk/crates/vino-transport", features = ["all"] }
logger = { path = "./crates/logger" }
test-vino-provider = { path = "./crates/integration/test-vino-provider" }
vino-rpc = { path = "./crates/vino-rpc" }
vino-macros = { path = "./sdk/crates/vino-macros" }
utils = { path = "./tests/utils" }
maplit = "1.0"
tokio = { version = "1.4", features = [
  "macros",
  "process",
  "time",
  "net",
  "rt-multi-thread",
] }
futures = "0.3"
log = "0.4"
test-logger = { path = "./crates/test-logger" }
anyhow = "1.0"
serde_json = "1.0"

# bench specific
criterion = { version = "0.3", features = ["async", "async_tokio"] }
once_cell = "1.8"
vino-host = { path = "./crates/vino-host" }
vino-random = { path = "./crates/vino-random" }

[workspace]
members = [
  "crates/forks/*",
  "crates/interfaces/*",
  "crates/integration/*",
  "crates/*",
]

exclude = [
  "crates/integration/test-wapc-component",
  "sdk/",
  "forks/",
  "crates/forks",
  "crates/integration",
  "crates/interfaces",
]

[[bench]]
name = "create-user"
harness = false

[[bench]]
name = "markdown"
harness = false
