[target.aarch64-unknown-linux-gnu]
image = "vinodotdev/cross:aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image = "vinodotdev/cross:x86_64-unknown-linux-gnu"

[target.aarch64-apple-darwin]
image = "vinodotdev/cross:aarch64-apple-darwin"

[target.x86_64-apple-darwin]
image = "vinodotdev/cross:x86_64-apple-darwin"

[target.x86_64-pc-windows-gnu]
image = "vinodotdev/cross:x86_64-pc-windows-gnu"

