[package]
name = "vino-lattice"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
wasmflow-interface = { path = "../../../sdk/crates/wasmflow-interface" }
wasmflow-invocation = { path = "../../../sdk/crates/wasmflow-invocation" }
nats = { version = "0.15" }
tracing = "0.1"
vino-rpc = { path = "../vino-rpc" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
wasmflow-packet = { path = "../../../sdk/crates/wasmflow-packet", features = [] }
wasmflow-entity = { path = "../../../sdk/crates/wasmflow-entity" }
wasmflow-codec = { path = "../../../sdk/crates/wasmflow-codec" }
thiserror = "1.0"
nkeys = "0.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["time", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
futures = "0.3"
parking_lot = "0.12"
once_cell = "1.5"

[dev-dependencies]
test-vino-provider = { path = "../../integration/test-vino-provider" }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
anyhow = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
pretty_assertions = "1.2"
