[package]
name = "vinoc"
version = "0.1.0"
edition = "2018"
default-run = "vinoc"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-packet = { path = "../vino-packet" }
vino-runtime = { path = "../vino-runtime" }
vino-transport = { path = "../vino-transport" }
vino-host = { path = "../vino-host" }
vino-manifest = { path = "../vino-manifest" }
vino-codec = { path = "../vino-codec" }
vino-rpc = { path = "../vino-rpc" }
vino-macros = { path = "../vino-macros" }
vino-entity = { path = "../vino-entity" }
vino-wascap = { path = "../vino-wascap" }
vino-types = { path = "../vino-types" }

logger = { path = "../logger" }
log = "0.4.11"
structopt = "0.3.21"
nkeys = "0.1.0"
futures = "0.3.13"
serde_json = "1.0.64"
thiserror = "1.0.24"
tokio = { version = "1.8.1", features = [
  "macros",
  "signal",
  "io-std",
  "rt-multi-thread",
  "io-util",
] }
tonic = { version = "0.5.0", features = ["tls"] }
atty = "0.2.14"

[dev-dependencies]
test_bin = "0.3.0"
maplit = "1.0.2"
test-env-log = "0.2.7"

[[bin]]
name = "vinoc"
path = "src/main.rs"
