[package]
name = "vinoc"
version = "0.3.2"
edition = "2018"
default-run = "vinoc"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-packet = { path = "../../sdk/crates/vino-packet" }
vino-runtime = { path = "../vino-runtime" }
vino-transport = { path = "../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-host = { path = "../vino-host" }
vino-manifest = { path = "../vino-manifest" }
vino-codec = { path = "../../sdk/crates/vino-codec" }
vino-rpc = { path = "../vino-rpc", features = ["client"] }
vino-macros = { path = "../../sdk/crates/vino-macros" }
vino-entity = { path = "../../sdk/crates/vino-entity" }
vino-wascap = { path = "../vino-wascap" }
vino-types = { path = "../../sdk/crates/vino-types" }

logger = { path = "../logger" }
tracing = "0.1"
structopt = "0.3.21"
nkeys = "0.1.0"
futures = "0.3.13"
serde_json = "1.0.64"
thiserror = "1.0.24"
tokio = { version = "1", features = [
  "macros",
  "signal",
  "io-std",
  "rt-multi-thread",
  "io-util",
] }
tonic = { version = "0.5", features = ["tls"] }
atty = "0.2.14"

[dev-dependencies]
test_bin = "0.3.0"
maplit = "1.0.2"
logger = { path = "../logger" }
test-logger = { path = "../test-logger" }

[[bin]]
name = "vinoc"
path = "src/main.rs"
