[package]
name = "vinoc"
version = "0.1.0"
edition = "2018"
default-run = "vinoc"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-component = { path="../vino-component" }
vino-runtime = { path="../vino-runtime" }
vino-transport = { path="../vino-transport" }
vino-host = { path="../vino-host" }
vino-manifest = { path="../vino-manifest" }
vino-codec = { path="../vino-codec" }
vino-rpc = { path="../vino-rpc" }
vino-macros = { path="../vino-macros" }
vino-entity = { path="../vino-entity" }
vino-wascap = { path="../vino-wascap" }
logger = { path="../logger" }
wapc = { version="0.10.1" }
chrono = "0.4.19"
colored = "2.0.0"
log = "0.4.11"
env_logger = "0.8.3"
actix-rt = "2.1.0"
structopt = "0.3.21"
nkeys = "0.1.0"
futures = "0.3.13"
serde_json = "1.0.64"
serde_yaml = "0.8.17"
serde = "1.0.126"
thiserror = "1.0.24"

tonic = { version="0.4.3", features=["tls"] }

[dev-dependencies]
test_bin = "0.3.0"
maplit = "1.0.2"
test-env-log = "0.2.7"

[[bin]]
name = "vinoc"
path = "src/main.rs"
