[package]
name = "vino-interfaces-collection"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-transport = { path = "../../vino-transport" }
vino-rpc = { path = "../../vino-rpc" }
vino-component = { path = "../../vino-component" }
vino-provider = { path = "../../vino-provider", features = ["native"] }
serde = { version = "1.0.118", features = ["derive"] }

[dev-dependencies]
