[package]
name = "vino-test"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tap = { path = "../tap" }
vino-transport = { path = "../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-entity = { path = "../../sdk/crates/vino-entity" }
vino-rpc = { path = "../vino-rpc" }
serde = { version = "1.0.118", features = ["derive"] }
serde-value = "0.7.0"
serde_yaml = "0.8.21"
thiserror = "1.0.29"
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread"] }
tokio-stream = "0.1.7"
tracing = "0.1"
