[package]
name = "vino-test"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde-value = "0.7.0"
serde_yaml = "0.8.21"
thiserror = "1.0.29"
