[package]
name = "vino-interface-collection"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["vino-provider/native"]
wasm = ["vino-provider/wasm"]

[dependencies]
vino-provider = { path = "../../../sdk/crates/vino-provider" }
serde = { version = "1.0.118", features = ["derive"] }

[dev-dependencies]
