schematics:
  - name: logger
    components:
      logger:
        id: vino-v0::log
    connections:
      - from:
          reference: <input>
          port: schem_input
        to:
          reference: logger
          port: log_input
      - from:
          reference: logger
          port: log_output
        to:
          reference: <output>
          port: schem_output
