[package]
name = "vino-runtime"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"

[features]

[dependencies]
wasmflow-interface = { path = "../../../sdk/crates/wasmflow-interface" }
wasmflow-streams = { path = "../../../sdk/crates/wasmflow-streams" }
wasmflow-invocation = { path = "../../../sdk/crates/wasmflow-invocation" }
wasmflow-packet = { path = "../../../sdk/crates/wasmflow-packet" }
wasmflow-macros = { path = "../../../sdk/crates/wasmflow-macros" }
wasmflow-output = { path = "../../../sdk/crates/wasmflow-output", features = [] }
wasmflow-codec = { path = "../../../sdk/crates/wasmflow-codec" }
wasmflow-entity = { path = "../../../sdk/crates/wasmflow-entity" }

vino-schematic-graph = { path = "../vino-schematic-graph" }
vino-interpreter = { path = "../vino-interpreter" }
vino-random = { path = "../vino-random" }
vino-manifest = { path = "../vino-manifest" }
vino-loader = { path = "../vino-loader" }
vino-provider-wasm = { path = "../vino-provider-wasm" }
vino-provider-lattice = { path = "../vino-provider-lattice" }
vino-provider-par = { path = "../vino-provider-par" }
vino-provider-grpc = { path = "../vino-provider-grpc" }
vino-lattice = { path = "../vino-lattice" }
vino-stdlib = { path = "../../providers/vino-stdlib" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-wascap = { path = "../vino-wascap" }
vino-rpc = { path = "../vino-rpc" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

futures = "0.3"
async-trait = "0.1.50"
once_cell = "1.8"
parking_lot = { version = "0.12", features = [] }
thiserror = "1.0"
tokio = { version = "1", features = [
  "macros",
  "time",
  "sync",
  "rt-multi-thread",
] }
tokio-stream = { version = "0.1", features = [] }
# itertools = "0.10"
tracing = "0.1"
# dyn-clone = "1.0.4"
# rand = { version = "0.8", default-features = false, features = [
#   "std_rng",
#   "alloc",
# ] }
uuid = "1.1"

[dev-dependencies]
vino-invocation-server = { path = "../vino-invocation-server" }
test-vino-provider = { path = "../../integration/test-vino-provider" }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
maplit = "1.0"
pretty_assertions = "1"
lazy_static = "1.4"
anyhow = "1.0"
runtime-testutils = { path = "./tests/runtime_utils" }
