[package]
name = "rot"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Results-only testing framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = { workspace = true }
k9 = { workspace = true }
