name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's wrong (at a high level)?
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
      description: What is the current behavior?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
      description: What was the expected behavior?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Add any logs or comments here
