[package]
name = "test-vino-provider"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[features]
default = ["native", "provider"]
provider = []
guest = []
wasm = ["vino-provider/wasm"]
native = ["vino-provider/native"]

[dependencies]
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-rpc = { path = "../../vino-rpc" }
vino-entity = { path = "../../../sdk/crates/vino-entity" }
vino-codec = { path = "../../../sdk/crates/vino-codec" }
vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-types = { path = "../../../sdk/crates/vino-types" }
serde = { version = "1.0.118", features = ["derive"] }
once_cell = "1.8"
async-trait = "0.1.50"
futures = "0.3.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
log = "0.4.14"

[dev-dependencies]
test-logger = { path = "../../test-logger" }
logger = { path = "../../logger" }
structopt = "0.3.21"
log = "0.4"
anyhow = "1.0.41"
