[package]
name = "test-vino-provider"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["provider", "guest"]
provider = []
guest = []

[dependencies]
wasmflow-sdk = { path = "../../../sdk/crates/wasmflow-sdk", features = ["v1"] }
vino-rpc = { path = "../../vino/vino-rpc" }
wasmflow-entity = { path = "../../../sdk/crates/wasmflow-entity" }
vino-transport = { path = "../../../sdk/crates/vino-transport" }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.50"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1"

[dev-dependencies]
futures = "0.3"
test-logger = { path = "../../misc/test-logger" }
tokio = { version = "1", features = ["macros"] }
logger = { path = "../../vino/logger" }
clap = { version = "3.0", features = ["derive", "env"] }
tracing = "0.1"
anyhow = "1.0"
pretty_assertions = "1.2"
