[package]
name = "vino-manifest"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
thiserror = "1.0.25"
tracing = "0.1.26"
hocon = "0.5.2"
serde_yaml = "0.8.17"
num-traits = "0.2.14"
enum-primitive-derive = "0.2.1"
serde-with-expand-env = "1.1.0"
serde_json = "1.0.64"
serde-value = "0.7.0"
regex = "1"
lazy_static = "1.4.0"

[dev-dependencies]
test-env-log = "0.2.7"
env_logger = "0.8.3"
tracing-subscriber = "0.2.18"
anyhow = "1.0.41"
pretty_assertions = "0.7.2"
