[package]
name = "vino-loader"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1.0.25"
oci-utils = { path = "../oci-utils" }
tokio = { version = "1", features = ["fs"] }
