[package]
name = "vino-stdlib"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"

[features]
default = ["provider"]
provider = []
guest = []

[dependencies]
vino-rpc = { path = "../../vino/vino-rpc" }
vino-random = { path = "../../vino/vino-random" }
wasmflow-sdk = { path = "../../sdk/wasmflow-sdk", features = ["v1"] }
vino-transport = { path = "../../sdk/vino-transport" }
wasmflow-packet = { path = "../../sdk/wasmflow-packet" }
wasmflow-entity = { path = "../../sdk/wasmflow-entity" }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0"
parking_lot = "0.12"


[dev-dependencies]
vino-stdlib = { path = ".", features = ["guest"] }
logger = { path = "../../vino/logger" }
test-logger = { path = "../../misc/test-logger" }
futures = "0.3"
vino-transport = { path = "../../sdk/vino-transport", features = ["all"] }
