[package]
name = "wasmtime-provider"
version = "0.0.3"
authors = ["waPC Team"]
edition = "2018"
exclude = [".assets"]
description = "A wasmtime engine provider for the waPC host"
license = "Apache-2.0"
homepage = "https://github.com/wapc/wasmtime-provider"
documentation = "https://docs.rs/wasmtime-provider"
readme = "README.md"
keywords = ["sdk", "wapc", "webassembly", "wasm", "wasmtime"]
categories = ["wasm", "api-bindings"]


[dependencies]
wapc = { path = "../wapc-rust" }
tracing = "0.1"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
wasmtime = { version = "0.30.0", features = ["cache"] }
wasmtime-wasi = "0.30.0"
anyhow = "1.0.31"
wasi-common = "0.30.0"
wasi-cap-std-sync = "0.30.0"
cap-std = "0.20.0"
parking_lot = "0.11.1"

[dev-dependencies]
env_logger = "0.9.0"
criterion = { version = "0.3.5", features = [] }
once_cell = "1.8.0"

[[bench]]
name = "basic"
harness = false
