[package]
name = "vino"
version = "0.3.1"
edition = "2021"
default-run = "vino"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmflow-invocation = { path = "../../sdk/wasmflow-invocation" }
cli-common = { path = "../cli-common" }
vino-random = { path = "../../vino/vino-random" }
vino-loader = { path = "../../vino/vino-loader" }
wasmflow-packet = { path = "../../sdk/wasmflow-packet" }
logger = { path = "../../vino/logger" }
vino-provider-cli = { path = "../../vino/vino-provider-cli" }
vino-runtime = { path = "../../vino/vino-runtime" }
vino-transport = { path = "../../sdk/vino-transport", features = ["all"] }
vino-host = { path = "../../vino/vino-host" }
vino-manifest = { path = "../../vino/vino-manifest" }
wasmflow-codec = { path = "../../sdk/wasmflow-codec" }
wasmflow-interface = { path = "../../sdk/wasmflow-interface" }
tap = { path = "../../misc/tap" }
vino-test = { path = "../../vino/vino-test" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
clap = { version = "3.0", features = ["derive"] }
nkeys = "0.2"
serde_json = "1.0"
serde = "1.0"
thiserror = "1.0"
atty = "0.2"

[dev-dependencies]
test_bin = "0.3"
trycmd = "0.13"

[[bin]]
name = "vino"
path = "src/main.rs"
