[package]
name = "logger"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "json",
  "time",
] }
tracing-bunyan-formatter = "0.3.0"
tracing-appender = "0.2.0"
xdg = "2.4"
time = { version = "0.3", features = ["formatting"] }
ansi_term = "0.12"

structopt = "0.3"
thiserror = "1.0"
