[package]
name = "vow"
version = "0.2.8"
edition = "2018"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-runtime = { path = "../vino-runtime" }
vino-rpc = { path = "../vino-rpc" }
vino-provider-cli = { path = "../vino-provider-cli" }
vino-packet = { path = "../../sdk/crates/vino-packet" }
vino-codec = { path = "../../sdk/crates/vino-codec" }
vino-wascap = { path = "../vino-wascap" }
vino-provider = { path = "../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-provider-wasm = { path = "../vino-provider-wasm" }
vino-transport = { path = "../../sdk/crates/vino-transport" }

structopt = "0.3.22"
serde_json = "1.0.64"
serde-value = "0.7.0"
tokio = { version = "1.8.1", features = [
  "io-std",
  "macros",
  "rt-multi-thread",
] }
futures = "0.3.15"
tokio-stream = "0.1.7"
serde = { version = "1.0.126", features = ["derive"] }
log = "0.4"
thiserror = "1.0.25"
atty = "0.2.14"

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../test-logger" }
test-vino-provider = { path = "../integration/test-vino-provider" }

maplit = "1.0.2"
anyhow = "1.0.42"

[[bin]]
name = "vow"
path = "src/main.rs"
