[package]
name = "vow"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-runtime = { path = "../vino-runtime" }
vino-rpc = { path = "../vino-rpc" }
vino-provider-cli = { path = "../vino-provider-cli" }
vino-component = { path = "../vino-component" }
vino-codec = { path = "../vino-codec" }
vino-wascap = { path = "../vino-wascap" }
vino-provider = { path = "../vino-provider" }
vino-provider-wasm = { path = "../vino-provider-wasm" }
vino-transport = { path = "../vino-transport" }
structopt = "0.3.22"
actix = "0.12.0"
serde_json = "1.0.64"

tokio = { version = "1.8.1", features = [
  "macros",
  "net",
  "signal",
  "rt-multi-thread",
] }
futures = "0.3.15"
tokio-stream = "0.1.7"
serde = { version = "1.0.126", features = ["derive"] }
async-stream = "0.3.2"
tracing = "0.1.26"
thiserror = "1.0.25"
async-trait = "0.1.50"
logger = { path = "../logger" }

[dev-dependencies]
test-env-log = "0.2.7"
test-vino-provider = { path = "../integration/test-vino-provider" }
env_logger = "0.9"
tracing-subscriber = "0.2.18"
maplit = "1.0.2"
anyhow = "1.0.42"

[[bin]]
name = "vow"
path = "src/main.rs"
