version: 0
network:
  schematics:
    - name: echo
      connections:
        - from:
            instance: <input>
            port: input
          to:
            instance: <output>
            port: output
