---
version: 0
network:
  schematics:
    - name: native_component
      instances:
        add:
          id: vino::math::add
        add2:
          id: vino::math::add
      connections:
        - from:
            instance: <input>
            port: left
          to:
            instance: add
            port: left
        - from:
            instance: <input>
            port: right
          to:
            instance: add
            port: right
        - from:
            instance: <input>
            port: right
          to:
            instance: add2
            port: right
        - from:
            instance: add
            port: output
          to:
            instance: add2
            port: left
        - from:
            instance: add2
            port: output
          to:
            instance: <output>
            port: output
