[package]
name = "flow-component"
version = "0.5.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Create components to execute in Wick runtimes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-packet = { workspace = true, features = ["invocation"] }
serde_json = { workspace = true }
futures = { workspace = true }
wick-interface-types = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
