[package]
name = "vino-provider-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wasmtime"]
wasmtime = ["wasmtime-provider"]
# wasm3 = ["wasm3-provider"]

[dependencies]
vino-rpc = { path = "../vino-rpc" }
vino-packet = { path = "../../sdk/crates/vino-packet" }
vino-entity = { path = "../../sdk/crates/vino-entity" }
vino-random = { path = "../vino-random" }
vino-codec = { path = "../../sdk/crates/vino-codec" }
vino-wascap = { path = "../vino-wascap" }
vino-loader = { path = "../vino-loader" }
vino-wapc = { path = "../../sdk/crates/vino-wapc", features = [] }
vino-transport = { path = "../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-types = { path = "../../sdk/crates/vino-types" }
vino-macros = { path = "../../sdk/crates/vino-macros" }
serde_json = "1.0"
derivative = "2.2"
tokio = { version = "1", features = ["fs"] }
parking_lot = "0.11"

# Forks until https://github.com/wapc/wapc-rust/pull/24 is resolved
# wasmtime-provider = { version = "0.0", optional = true, features = ["cache"] }
# wapc = "0.10.1"
wasmtime-provider = { path = "../../forks/wasmtime-provider", optional = true, features = [
  "cache",
] }
wapc = { path = "../../forks/wapc-rust" }

tokio-stream = "0.1.7"
async-stream = "0.3.2"
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1.50"

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../test-logger" }
futures = "0.3"
maplit = "1.0"
anyhow = "1.0"
