[package]
name = "vino-provider-wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wasmtime"]
wasmtime = ["wasmtime-provider"]
wasm3 = ["wasm3-provider"]

[dependencies]
vino-rpc = { path = "../vino-rpc" }
vino-component = { path = "../vino-component" }
vino-codec = { path = "../vino-codec" }
vino-wascap = { path = "../vino-wascap" }
vino-provider = { path = "../vino-provider", features = ["native"] }
vino-transport = { path = "../vino-transport" }
vino-types = { path = "../vino-types" }
vino-macros = { path = "../vino-macros" }
oci-utils = { path = "../oci-utils" }
structopt = "0.3.22"
actix-rt = "2.2.0"
actix = "0.12.0"
serde_json = "1.0.64"
derivative = "2.2.0"
tokio = { version = "1.4.0", features = ["fs"] }
parking_lot = "0.11.1"

# wasm3-provider = { version="0.0.2", optional=true }
# wasmtime-provider = { version = "0.0.3", optional = true }
wasm3-provider = { path = "../forks/wasm3-provider", optional = true }
wasmtime-provider = { path = "../forks/wasmtime-provider", optional = true }
wapc = { path = "../forks/wapc-rust" }

futures = "0.3.15"
tokio-stream = "0.1.7"
serde = { version = "1.0.126", features = ["derive"] }
async-stream = "0.3.2"
tracing = "0.1.26"
thiserror = "1.0.25"
async-trait = "0.1.50"
logger = { path = "../logger" }

[dev-dependencies]
test-env-log = "0.2.7"
test-vino-provider = { path = "../integration/test-vino-provider" }
env_logger = "0.9"
tracing-subscriber = "0.2.18"
maplit = "1.0.2"
anyhow = "1.0.42"
