[package]
name = "vino-provider-wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wasmtime"]
wasmtime = ["wasmtime-provider"]
# wasm3 = ["wasm3-provider"]

[dependencies]
vino-rpc = { path = "../vino-rpc" }
vino-packet = { path = "../../sdk/crates/vino-packet" }
vino-random = { path = "../vino-random" }
vino-codec = { path = "../../sdk/crates/vino-codec" }
vino-wascap = { path = "../vino-wascap" }
vino-loader = { path = "../vino-loader" }
vino-provider = { path = "../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-transport = { path = "../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-types = { path = "../../sdk/crates/vino-types" }
vino-macros = { path = "../../sdk/crates/vino-macros" }
structopt = "0.3.22"
serde_json = "1.0.64"
derivative = "2.2.0"
tokio = { version = "1", features = ["fs"] }
parking_lot = "0.11.1"

# Forks until https://github.com/wapc/wapc-rust/pull/24 is resolved
# wasmtime-provider = { version = "0.0.7", optional = true, features = ["cache"] }
# wapc = "0.10.1"
# wasmtime-provider = { path = "../../forks/wasmtime-provider", optional = true, features = [
#   "cache",
# ] }
# wapc = { path = "../../forks/wapc-rust" }
wasmtime-provider = { path = "../../../wapc/crates/wasmtime-provider", optional = true, features = [
  "cache",
] }
wapc = { path = "../../../wapc/crates/wapc-rust" }

futures = "0.3.15"
tokio-stream = "0.1.7"
async-stream = "0.3.2"
log = "0.4"
thiserror = "1.0.25"
async-trait = "0.1.50"

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../test-logger" }
test-vino-provider = { path = "../integration/test-vino-provider" }

maplit = "1.0.2"
anyhow = "1.0.42"
