[package]
name = "oci-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oci-distribution = { path = "../../../forks/oci-distribution", features = [
  "rustls-tls",
], default-features = false }
# oci-distribution = { version = "0.8.1", features = [
#   "rustls-tls",
# ], default-features = false }
thiserror = "1.0"
tracing = "0.1"
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
test-log = "0.2"
env_logger = "0.9"
anyhow = "1.0"
structopt = "0.3"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
tar = "0.4.38"
async-recursion = "1.0"
