[package]
name = "vino-keyvalue-redis"
version = "0.0.0"
edition = "2021"

[features]
default = ["provider"]
provider = []

[dependencies]
wasmflow-sdk = { path = "../../../sdk/crates/wasmflow-sdk", features = ["v1"] }
wasmflow-entity = { path = "../../../sdk/crates/wasmflow-entity", features = [] }
vino-provider-cli = { path = "../../vino/vino-provider-cli" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
wasmflow-packet = { path = "../../../sdk/crates/wasmflow-packet" }
vino-rpc = { path = "../../vino/vino-rpc" }
wasmflow-macros = { path = "../../../sdk/crates/wasmflow-macros" }
vino-interface-keyvalue = { path = "../../interfaces/interface-keyvalue", features = [
  "provider",
  "guest",
] }
redis = { version = "0.21", features = ["tokio-comp"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["macros", "sync", "rt-multi-thread"] }
once_cell = "1.8"
tokio-util = { version = "0.7", features = ["codec"] }
clap = { version = "3.0", features = ["derive", "env"] }
tracing = "0.1"
tracing-futures = "0.2"

[dev-dependencies]
logger = { path = "../../vino/logger" }
serde_json = "1.0"
tonic = "0.7"
rand = "0.8"
anyhow = "1.0"
test-logger = { path = "../../misc/test-logger" }
