[package]
name = "vino-collection-inmemory"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.25"
vino-provider = { path="../vino-provider" }
vino-runtime = { path="../vino-runtime" }
vino-guest = { path="../vino-guest" }
log = "0.4.14"
serde = { version="1.0.118", features=["derive"] }
lazy_static = "1.4.0"
async-trait = "0.1.50"
futures = "0.3.15"
tokio = { version="1.4.0", features=["macros", "rt-multi-thread"] }


[dev-dependencies]
maplit = "1.0.2"
test-env-log = "0.2.7"
env_logger = "0.8.4"
