[package]
name = "vino-interface-keyvalue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["native", "provider"]
provider = []
guest = []
wasm = ["vino-provider/wasm"]
native = ["vino-provider/native"]

[dependencies]
vino-provider = { path = "../../../sdk/crates/vino-provider", default-features = false }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
