[package]
name = "vino-interface-keyvalue"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-transport = { path = "../../../sdk/crates/vino-transport" }
vino-rpc = { path = "../../vino-rpc" }
vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
serde = { version = "1.0.118", features = ["derive"] }

[dev-dependencies]
