[package]
name = "vino-par"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
tracing = "0.1"
serde_json = "1"
serde_yaml = "0.8"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0"
tar = "0.4.38"
tokio = { version = "1", features = ["fs"] }

vino-types = { path = "../../../sdk/crates/vino-types" }
vino-wascap = { path = "../vino-wascap" }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
clap = { version = "3.0", features = ["derive", "env"] }
async-recursion = "1.0"
env_logger = "0.9"
