[package]
name = "vino-provider-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-rpc = { path="../vino-rpc" }
vino-component = { path="../vino-component" }
vino-codec = { path="../vino-codec" }
tonic = { version="0.4.3", features=["tls"] }
prost = "0.7.0"
tokio = { version="1.4.0", features=["macros", "net", "rt-multi-thread"] }
futures = "0.3.15"
tokio-stream = "0.1.6"
serde = { version="1.0.118", features=["derive"] }
async-stream = "0.3.2"
rand = "0.8.4"
tracing = "0.1.26"
thiserror = "1.0.25"

[build-dependencies]
tonic-build = { version="0.4.2", features=["prost"] }

[dev-dependencies]
test-env-log = "0.2.7"
test-vino-provider = { path="../test-vino-provider" }
env_logger = "0.8.4"
tracing-subscriber = "0.2.18"
