[package]
name = "vino-test"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tap = { path = "../../misc/tap" }
wasmflow-invocation = { path = "../../../sdk/crates/wasmflow-invocation" }
wasmflow-packet = { path = "../../../sdk/crates/wasmflow-packet", features = [] }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
wasmflow-entity = { path = "../../../sdk/crates/wasmflow-entity" }
vino-rpc = { path = "../vino-rpc" }
serde = { version = "1.0", features = ["derive"] }
serde-value = "0.7.0"
serde_yaml = "0.8"
thiserror = "1.0"
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread"] }
tokio-stream = "0.1.7"
tracing = "0.1"
