[package]
name = "vino-rpc"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-component = { path="../vino-component" }
vino-codec = { path="../vino-codec" }
vino-entity = { path="../vino-entity" }
vino-transport = { path="../vino-transport" }
tonic = { version="0.4.3", features=["tls"] }
prost = "0.7.0"
prost-types = "0.7.0"
tokio = { version="1.4.0", features=["macros", "net", "rt-multi-thread"] }
futures = "0.3.15"
tokio-stream = { version="0.1.6", features=["net"] }
serde = { version="1.0.118", features=["derive"] }
async-stream = "0.3.2"
rand = "0.8.4"
tracing = "0.1.26"
thiserror = "1.0.25"
async-trait = "0.1.50"
derivative = "2.2.0"

[build-dependencies]
tonic-build = { version="0.4.2", features=["prost"] }

[dev-dependencies]
test-env-log = "0.2.7"
