---
version: "0"
network:
  schematics:
    - name: main
      instances:
        logger: vino::v0::log
        eq: vino::v0::string_equals
        branch:
          id: vino::v0::branch
          config:
            ok: self::good
            else: self::bad
            inputs:  ["actual"]
            outputs: ["output"]
      connections:
        - <> => logger[input]
        - logger[output] => eq[actual]
        - "EXPECTED" => eq[expected]
        - eq[result] => <branch>[condition]
        - eq[actual] => <branch.inputs>[actual]
        - branch[output] -> <>
   - name: good
      instances:
        cat: vino::v0::concatenate
      connections:
        - <>[actual] => cat[right]
        - "OK_" => cat[left]
        - cat[output] => <>
   - name: bad
      instances:
        cat: vino::v0::concatenate
      connections:
        - <>[actual] => cat[right]
        - "OK_" => cat[left]
        - cat[output] => <>
