[package]
name = "vino-host"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]


[dependencies]
wasmflow-interface = { path = "../../../sdk/crates/wasmflow-interface", features = [] }
wasmflow-invocation = { path = "../../../sdk/crates/wasmflow-invocation" }
vino-random = { path = "../vino-random" }
vino-runtime = { path = "../vino-runtime" }
vino-lattice = { path = "../vino-lattice" }
vino-manifest = { path = "../vino-manifest" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
wasmflow-output = { path = "../../../sdk/crates/wasmflow-output", features = [] }
vino-loader = { path = "../vino-loader" }
vino-provider-cli = { path = "../vino-provider-cli" }
wasmflow-codec = { path = "../../../sdk/crates/wasmflow-codec" }
vino-rpc = { path = "../vino-rpc" }
vino-invocation-server = { path = "../vino-invocation-server" }
wasmflow-entity = { path = "../../../sdk/crates/wasmflow-entity" }
wasmflow-macros = { path = "../../../sdk/crates/wasmflow-macros" }
tracing = "0.1"

thiserror = "1.0"
nkeys = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
http = "0.2"
once_cell = "1.8"
parking_lot = "0.12"
uuid = "1.1"

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
tokio = { version = "1", features = [
  "net",
  "rt-multi-thread",
  "time",
  "io-std",
  "io-util",
  "macros",
] }
anyhow = "1.0"
tokio-stream = "0.1.7"
