[package]
name = "vino-random"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.4", default-features = false, features = [
  "std_rng",
  "alloc",
] }
rand_chacha = "0.3.1"
parking_lot = "0.11.2"
uuid = { version = "0.8.2", features = ["v4"] }
