[package]
name = "oci-utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oci-distribution = "0.7.0"
thiserror = "1.0.26"
tracing = "0.1"
